chore: test 2

diff --git a/.github/workflows/lint-pr.yml b/.github/workflows/lint-pr.yml
--- a/.github/workflows/lint-pr.yml
+++ b/.github/workflows/lint-pr.yml
@@ -98,7 +98,4 @@ jobs:
       - name: 'Check translations'
         run: |
           diff_lang=$(git diff -U0 --color | grep '^\e\[[^m]*m[-+]' | grep -Ev '(--- a/|\+\+\+ b/)')
-          if [ -n "$diff_lang" ]; then
-            echo "::error Update translations:\n$diff_lang" 
-            exit 1
-          fi
+          [ -z "$diff_lang" ] || (echo "::error Update translations:\n$diff_lang"  && exit 1)
