chore: test 28
(cherry picked from commit 219f28f9965bcd6b9fa13e712cc4346c92b692f0)

diff --git a/.github/workflows/lint-pr.yml b/.github/workflows/lint-pr.yml
--- a/.github/workflows/lint-pr.yml
+++ b/.github/workflows/lint-pr.yml
@@ -102,7 +102,6 @@ jobs:
           echo "diff-lang=$diffLang" >> $GITHUB_OUTPUT  
 
       - name: 'Check github-script'
-        shell: bash
         run: |
           diff_lang=$(git diff -U0 --color | grep '^\e\[[^m]*m[-+]' | grep -Ev '(--- a/|\+\+\+ b/)') \
-          git diff --quiet || (echo "::error ::Update translations:\n$diff_lang" && exit 1)
+          git diff --quiet || (echo "::error ::Update translations: $diff_lang" && exit 1)
