chore: test 8

diff --git a/.github/workflows/lint-pr.yml b/.github/workflows/lint-pr.yml
--- a/.github/workflows/lint-pr.yml
+++ b/.github/workflows/lint-pr.yml
@@ -98,4 +98,4 @@ jobs:
       - name: 'Check translations'
         run: |
           diff_lang=$(git diff -U0 --color | grep '^\e\[[^m]*m[-+]' | grep -Ev '(--- a/|\+\+\+ b/)')
-          echo "::error::Filename $diff_lang doesn't match possible files" && exit 1
+          echo "::error::Filename doesn't match possible files" && exit 1
