chore: test

diff --git a/.github/workflows/lint-pr.yml b/.github/workflows/lint-pr.yml
--- a/.github/workflows/lint-pr.yml
+++ b/.github/workflows/lint-pr.yml
@@ -99,5 +99,6 @@ jobs:
         run: |
           diff_lang=$(git diff -U0 --color | grep '^\e\[[^m]*m[-+]' | grep -Ev '(--- a/|\+\+\+ b/)')
           if [ -n "$diff_lang" ]; then
-            (echo "Update translations:\n$diff_lang" && exit 1)
+            echo "::error Update translations:\n$diff_lang" 
+            exit 1
           fi
