chore: test 9

diff --git a/.github/workflows/lint-pr.yml b/.github/workflows/lint-pr.yml
--- a/.github/workflows/lint-pr.yml
+++ b/.github/workflows/lint-pr.yml
@@ -98,4 +98,12 @@ jobs:
       - name: 'Check translations'
         run: |
           diff_lang=$(git diff -U0 --color | grep '^\e\[[^m]*m[-+]' | grep -Ev '(--- a/|\+\+\+ b/)')
-          echo "::error::Filename doesn't match possible files" && exit 1
+          if [[ -n $diff_lang ]]; then
+            echo "::group::git diff -U0"
+            echo "::error::Update translations:\n$diff_lang! Please run \`npm run generate:i18n\` and commit the result."
+            git diff 
+            echo "::endgroup::"
+            exit 1
+          else
+            echo "min constraints file is up to date."
+          fi
