chore: test 50

diff --git a/.github/workflows/lint-pr.yml b/.github/workflows/lint-pr.yml
--- a/.github/workflows/lint-pr.yml
+++ b/.github/workflows/lint-pr.yml
@@ -100,5 +100,5 @@ jobs:
           diff_locales=$(git diff ./public/locales | grep '^[+-][^+-]')          
           if [ -n "$diff_locales" ]; then
             echo "::warning::Missing translations: $diff_locales"
-            (echo "::error::Some translations are missing. Please add these translations in the repository" | exit 1)
+            (echo "::error::Some translations are missing. Please add these translations in the repository" && exit 1)
           fi
